### PR TITLE
session: allow custom SNIs for very rare situations

### PR DESCRIPTION
**Pull request by natasha-jarus**
In 100% of customer use cases the SNI set by ngrok-go is correct. However, in the case that someone decides to, say, hard-code an IP address for the tunnel ingress (or otherwise do the DNS lookup for it before calling the agent), they may want to set an appropriate SNI so the server can validate the tls cert.

We use this feature internally as part of our end to end test suite. :)

### CODE REVIEW

**Review by euank — APPROVED** [review]
:+1:

**Comment by euank** [comment]
I'll comment that there might be a better change instead: `WithTLSConfig(*tls.Config)` (or `WithTLSDialer`)

Someone might wish to override more parts of the TLS config, and it seems quite reasonable to allow that too for similar unusual cases.

**Review by jrobsonchase — APPROVED** [review]
LGTM as well :+1: 

Agreed with @euank that being able to provide a full tls config would probably be useful as well - that's what we do over in Rust land. It lets library consumers make whatever tweaks are needed, and then if we find ourselves repeating a pattern over and over, we add shortcuts.

**Comment by natasha-jarus** [comment]
superseded by #85

**Pull request closed without merging**
